#include "ArtReader.hpp"
#include "ArtReader.hpp"
#include "ArtReader.hpp"
#include "ArtReader.hpp"
/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include <Arcanum/Formats/Art/ArtReader.hpp>
#include <assert.h>

using namespace Arcanum;
using namespace Pollux;

ArtReader::ArtReader() :
	_Reader(NULL),
	_Frames(0)
{
}

void ArtReader::Reset(MemoryReader* reader)
{
	assert(reader != NULL);

	_Reader = reader;

	LoadHeader();
}

size_t ArtReader::Frames()
{
	return _Frames;
}

void ArtReader::Frame(size_t index, std::vector<unsigned char>& artBuffer, std::vector<unsigned char>& rgbBuffer)
{
	size_t offset = _FrameOffset.at(index);
	size_t size   = _FrameHeader.at(index).size;
	size_t width  = _FrameHeader.at(index).width;
	size_t height = _FrameHeader.at(index).height;

	_Reader->Offset(offset);

	artBuffer.resize(size);

	_Reader->Read(&artBuffer[0], size);

	rgbBuffer.resize(width * height * 4);

	size_t j = 0;

	if ((width * height) == size)
	{
		for (size_t i = 0; i < size; i++)
		{
			unsigned char src = artBuffer.at(i);

			if (src != 0)
			{
				rgbBuffer.at(j + 0) = _Pallete[0].colors[src].r;
				rgbBuffer.at(j + 1) = _Pallete[0].colors[src].g;
				rgbBuffer.at(j + 2) = _Pallete[0].colors[src].b;
				rgbBuffer.at(j + 3) = 255;
			}
			else
			{
				rgbBuffer.at(j + 0) = 0;
				rgbBuffer.at(j + 1) = 0;
				rgbBuffer.at(j + 2) = 0;
				rgbBuffer.at(j + 3) = 0;
			}

			j += 4;
		}
	}
	else
	{
		for (size_t i = 0; i < size; i++)
		{
			unsigned char ch = artBuffer.at(i);

			if (ch & 0x80)
			{
				int to_copy = ch & (0x7F);
				
				while (to_copy--)
				{
					i++;

					unsigned char src = artBuffer.at(i);

					if (src != 0)
					{
						rgbBuffer.at(j + 0) = _Pallete[0].colors[src].r;
						rgbBuffer.at(j + 1) = _Pallete[0].colors[src].g;
						rgbBuffer.at(j + 2) = _Pallete[0].colors[src].b;
						rgbBuffer.at(j + 3) = 255;
					}
					else
					{
						rgbBuffer.at(j + 0) = 0;
						rgbBuffer.at(j + 1) = 0;
						rgbBuffer.at(j + 2) = 0;
						rgbBuffer.at(j + 3) = 0;
					}

					j += 4;
				}
			}
			else
			{
				int to_clone = ch & (0x7F);

				i++;

				unsigned char src = artBuffer.at(i);

				while (to_clone--)
				{
					if (src != 0)
					{
						rgbBuffer.at(j + 0) = _Pallete[0].colors[src].r;
						rgbBuffer.at(j + 1) = _Pallete[0].colors[src].g;
						rgbBuffer.at(j + 2) = _Pallete[0].colors[src].b;
						rgbBuffer.at(j + 3) = 255;
					}
					else
					{
						rgbBuffer.at(j + 0) = 0;
						rgbBuffer.at(j + 1) = 0;
						rgbBuffer.at(j + 2) = 0;
						rgbBuffer.at(j + 3) = 0;
					}

					j += 4;
				}
			}
		}
	}
}

int ArtReader::Width(size_t index)
{
	return _FrameHeader.at(index).width;
}

int ArtReader::Height(size_t index)
{
	return _FrameHeader.at(index).height;
}

int ArtReader::Size(size_t index)
{
	return _FrameHeader.at(index).size;
}

const ArtTable& ArtReader::Palette()
{
	return _Pallete[0];
}

void ArtReader::LoadHeader()
{
	_Reader->Read(&_ArtHeader, sizeof(ArtHeader));

	_Frames = _ArtHeader.frame_num;

	int palettes = 0;
	
	for (size_t i = 0; i < ArtHeader::PaletteMax; i++)
	{
		ArtColor color = _ArtHeader.stupid_color[i];

		if ((color.a | color.b | color.g | color.r) != 0)
		{
			palettes++;
		}	
	}

	if (palettes > 0)
	{
		_Reader->Read(&_Pallete[0], sizeof(ArtTable));
	}

	if (palettes > 1)
	{
		_Reader->Read(&_Pallete[1], sizeof(ArtTable));
	}

	if (palettes > 2)
	{
		_Reader->Read(&_Pallete[2], sizeof(ArtTable));
	}

	bool animated = ((_ArtHeader.h0[0] & 0x1) == 0);

	if (animated)
	{
		_Frames *= 8;
	}

	_FrameHeader.clear();

	for (size_t j = 0; j < _Frames; j++)
	{
		ArtFrameHeader frameHeader;

		_Reader->Read(&frameHeader, sizeof(ArtFrameHeader));

		_FrameHeader.push_back(frameHeader);
	}

	_FrameOffset.clear();

	size_t offset = _Reader->Offset();

	_FrameOffset.push_back(offset);

	for (size_t k = 1; k < _FrameHeader.size(); k++)
	{
		offset += _FrameHeader.at(k).size;

		_FrameOffset.push_back(offset);
	}
}
