/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef litecpp_std_pmr_vector_hpp
#define litecpp_std_pmr_vector_hpp

#include <litecpp/base_vector.hpp>

namespace std
{
	namespace pmr
	{
		template <typename T>
		class vector
		{
		public:
			vector(memory_resource* source) :
				_base_vector(source)
			{
			}

			vector() :
				_base_vector(NULL)
			{
			}

			~vector()
			{
			}

			size_t capacity() const
			{
				return _base_vector.capacity();
			}

			size_t size() const
			{
				return _base_vector.size();
			}

			const T* data() const
			{
				return _base_vector.data();
			}

			T* data()
			{
				return _base_vector.data();
			}

			void reserve(size_t count)
			{
				_base_vector.reserve(count);
			}

			void resize(size_t count)
			{
				_base_vector.resize(count);
			}

			void clear()
			{
				_base_vector.clear();
			}

			void push_back(const T& element)
			{
				_base_vector.push_back(element);
			}

			const T& at(size_t index) const
			{
				return _base_vector.at(index);
			}

			const T& operator[] (size_t index) const
			{ 
				return _base_vector[index];
			}

			T& operator[] (size_t index)
			{
				return _base_vector[index];
			}

		private:
			litecpp::base_vector<T> _base_vector;
		};
	}
}

#endif 
