/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef Pollux_Allocators_Allocator_hpp
#define Pollux_Allocators_Allocator_hpp

#include <limits>

namespace Pollux
{
    template <class T> class allocator;

    template <>
    class allocator<void>
    {
    public:
        typedef void        value_type;
        typedef value_type* pointer;
        typedef value_type  const* const_pointer;
        typedef size_t      size_type;
        typedef ptrdiff_t   difference_type;

        template <class U>
        struct rebind
        {
            typedef allocator<U> other;
        };
    };

    template <class T>
    class allocator
    {
    public:
        typedef T            value_type;
        typedef value_type&  reference;
        typedef value_type   const& const_reference;
        typedef value_type*  pointer;
        typedef value_type   const* const_pointer;
        typedef size_t       size_type;
        typedef ptrdiff_t    difference_type;

        template <class U>
        struct rebind
        {
            typedef allocator<U> other;
        };

        allocator() throw() {}
        template <class U>
        allocator(allocator<U> const& u) throw() {}

        pointer allocate(size_type n, allocator<void>::const_pointer = 0)
        {
            return static_cast<pointer>(::operator new (n * sizeof(value_type)));
        }

        void deallocate(pointer p, size_type)
        {
            ::operator delete(p);
        }

        void construct(pointer p, value_type const& val)
        {
            ::new(p) value_type(val);
        }

        void destroy(pointer p)
        {
            p->~value_type();
        }

        size_type max_size() const throw()
        {
            return std::numeric_limits<size_type>::max() / sizeof(value_type);
        }

        pointer address(reference x) const
        {
            return &x;
        }

        const_pointer address(const_reference x) const
        {
            return &x;
        }
    };

    template <class T, class U>
    bool operator==(allocator<T> const&, allocator<U> const&)
    {
        return true;
    }

    template <class T, class U>
    bool operator!=(allocator<T> const& x, allocator<U> const& y)
    {
        return !(x == y);
    }
}

#endif
